config/routes.rb
UserPosts::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    delete 'logout' => :destroy
    post 'login' => :create
  end

  resources :users, :only => [:new, :create, :index] do
    resources :posts, :except => [:edit, :update]
  end

  controller :posts do
    get 'posts' => :index_all
    get 'posts/more_posts' => :more_posts
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"
  root :to => "posts#index_all"
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user, :inverse_of => :posts

  validates :user_id, :presence => true
  validates :title,   :presence => true, :length => {:maximum => 140}

  class << self
    def feed_index_all(limit=nil)
      posts = Post.joins(:user).
                order("posts.created_at desc").
                select("posts.id, users.id as user_id, users.full_name, posts.title, posts.created_at")
      posts = posts.limit(limit) if limit.present?
      posts
    end

    def index_all(limit=nil)
      posts = Post.order('created_at desc')
      posts = posts.limit(limit) if limit.present?
      posts
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, :inverse_of => :user, :dependent => :destroy

  # username contains letters or digits and its length is from 3 to 12
  validates :username,  :format => /^[a-zA-Z0-9]{3,12}$/, :uniqueness => true

  validates :password, :presence => true

  # full_name contains letters or _ or - or space, it has to start from letter and minimum lengths is 5 and maximum 30
  validates :full_name, :format => /^[a-zA-Z][ a-zA-Z_-]{4,29}$/

  validates :phone,     :format => { :with => /^\d{7,20}$/, :message => 'Has to have 7 to 20 digits' }

end

app/models/user_posts_settings.rb
class UserPostsSettings < Settingslogic
  source "#{Rails.root}/config/user_posts.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :authenticate

  protect_from_forgery

  helper_method :current_user

  # Returns the instance of the authenticated user. Otherwise, it returns nil.
  # This is a useful / helper method that will allow other modules to
  # get access to authenticated user object.
  #
  def current_user
    User.find_by_id(session[:user_id]) if session[:user_id].present?
  end

  def log_user_in (user)
    session[:user_id]= user.id unless user.nil?
  end

  ##################################################
  protected

  # This method will be called before every controller action on any controller
  # that derives from +ApplicationController+.
  # What it does is to authenticate the user, i.e. to find who the user that
  # is trying the action is. If he cannot find, he will redirect to login page
  # in order to ask user to enter username and password. As soon as the user
  # enters a valid username / password, he will be redirected back to
  # where he wanted to go (+request.fullpath+))
  # If authentication takes place, we are happy and return true.
  #
  def authenticate
    user = nil
    user = User.find_by_id(session[:user_id]) if session[:user_id].present?
    if !user.present?
      session[:user_id] = nil
      flash[:alert] = "You must be logged in to access this page"
      redirect_to login_path(:return_to => request.fullpath)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # We will not authenticate the user that is trying to see the Posts.
  skip_before_filter :authenticate, :only => [:index, :index_all, :show, :more_posts]

  # Creation and Deletion of post, requires authorization. A user can delete only the
  # posts that he owns. Also, he can create posts only under his account.
  before_filter :authorize, :only => [:create, :destroy]

  # GET /users/:user_id/posts/new
  #
  # This is requesting the form to create a new post
  def new
    @post = Post.new(:user => current_user)
  end

  # POST /users/:user_id/posts
  #
  # This is accepting the post data when creating a new post and saves the post into db
  def create
    if (@post = Post.create(params[:post]) { |p| p.user_id = params[:user_id].to_i }) && @post.valid?
      flash.now[:notice] = 'Post has been created sccessfully'
      render :show
    else
      flash.now[:alert] = 'Cannot create post'
      render :new, :status => :unprocessable_entity
    end
  end

  # GET /users/:user_id/posts
  #
  # Returns all the posts of the user defined
  def index
    user = User.find(params[:user_id])
    @posts = user.posts.order("created_at desc")
  end

  # GET /users/:user_id/posts/:id
  #
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts?limit=X
  #
  # Gets all posts from all users
  def index_all
    limit = params[:limit].present? ? params[:limit].to_i : nil
    respond_to do |format|
      format.html {
        @posts = Post.index_all(limit)
        render :index
      }
      format.rss {
        @posts = Post.feed_index_all(limit)
        render :index, :layout => false
      }
    end
  end

  # DELETE /users/:user_id/posts/:id
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.env["HTTP_REFERER"] || user_posts_path(current_user), :notice => "Post deleted successfully"
  rescue ActiveRecord::ActiveRecordError => ex
    logger.error ex.message
    logger.error ex.backtrace

    flash.now[:alert] = "Cannot delete post, ex: #{ex.message}"
    render :show, :status => :unprocessable_entity
  end

  # GET /posts/more_posts?count=1 where count is the number of posts in view
  #
  # Returns the number of posts that are not displayed in the view.
  def more_posts
    count = 0
    count = params[:count].to_i if params[:count].present?
    current_count = Post.count
    @answer = 0
    @answer = current_count - count
    render :layout => false
  end

  ##############################

  protected

  def authorize
    # authorization check. User that is posting should be the one logged in
    unless current_user.present? && params[:user_id].to_i == current_user.id
      flash[:alert] = 'You do not have permssion to access this page'
      redirect_to login_path(:return_to => request.fullpath), :notice => "You have to log in"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # We will not authenticate the user that is trying to login (actions 'new' and 'create'),
  # or that is loggin out (action 'destroy')
  skip_before_filter :authenticate, :only => [:new, :create, :destroy]

  # GET /login
  #
  # Invoked when user requests the page to login
  def new
  end

  # Delete /logout
  #
  # Invoked when user wants to logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # POST /login
  #
  # Invoked when user posts data over the page to login
  def create
    if ( user = User.find_by_username(params[:username]) ) && user.password == params[:password]
      log_user_in(user)
      redirect_to params[:return_to] || root_path, :notice => "You have successfully logged in"
    else
      flash.now[:alert] = "Invalid credentials. Please, try again"
      render :new, :status => :forbidden
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # We will not authenticate the user that is trying to Sign Up (actions 'new' and 'create'),
  # or that is trying to see the list of registered users
  skip_before_filter :authenticate, :only => [:new, :create, :index]

  # GET /users/new
  #
  # This will feed the sign up form
  def new
    @user = User.new
  end

  # POST /users
  #
  # This is used to create a user in db. Handles posting of Sign Up form.
  def create
    @user = User.new(params[:user])
    if @user.save
      # we log him in and we redirect to root path
      log_user_in(@user)
      redirect_to root_path, :notice => "You have successfully signed up."
    else
      flash.now[:alert] = "Cannot sign you up. Sorry for that."
      render :new, :status => :unprocessable_entity
    end
  end

  # GET /users
  def index
    @users = User.order("full_name")
  end

end

app/views/layouts/_logged_in_user.html.erb
<%= "Logged in as: " + current_user.username if current_user %><br/>
<%= link_to "Logout", logout_path, :method => :delete if current_user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= UserPostsSettings.application_name %></title>

  <%= stylesheet_link_tag "application" %>

  <%= javascript_include_tag "application" %>
  <%= yield :javascript_includes %>

  <%= auto_discovery_link_tag %>

  <%= csrf_meta_tag %>
</head>
<body>

<div id="menu">
    <%= content_tag :div, (link_to "Sign Up", new_user_path), :class => "menu_item" %>
    <%= content_tag :div, (link_to "Sign In", login_path), :class => "menu_item" unless current_user %>
    <%= content_tag :div, (link_to "Registered Users", users_path), :class => "menu_item" %>
    <%= content_tag :div, (link_to "Post", new_user_post_path(current_user)), :class => "menu_item" if current_user %>
    <%= content_tag :div, (link_to "All Posts", root_path), :class => "menu_item" %>
    <%= content_tag :div, (link_to "My Posts", user_posts_path(current_user)), :class => "menu_item" if current_user %>
    <%= content_tag :div, (link_to "Subscribe to RSS Feeds", posts_path(:format => :rss)), :class => "menu_item" %>
</div>

<div id="flash">
    <% flash.each do |type, message| -%>
      <% type = :error if type == :alert %>
      <div class="message <%= type %> closable">
        <p><%= message %></p>
      </div>
    <% end -%>
</div>

<%= yield %>

<div id="logged_in_user">
    <%= render :partial => "layouts/logged_in_user" %>
</div>

<div id="footer">

</div>

</body>
</html>

app/views/posts/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "posts" %>
<% end %>

<h1>Posts</h1>
<%= link_to "Check for posts", posts_more_posts_path(:count => @posts.length), :id => "check_for_posts", :remote => true, 'data-type' => "text/html" %>

<div id="more_posts_notification">
</div>

<div id="table_with_posts">
    <table>
        <tr>
            <th>Index</th>
            <th>Id</th>
            <th>Name</th>
            <th>Title</th>
            <th>Date Published</th>
            <th></th>
        </tr>
        <% index_position = 0 %>
        <% @posts.each do |p| %>

          <% index_position += 1 %>
          <tr>
              <td><%= index_position %></td>
              <td><%= p.id %></td>
              <td><%= p.user.full_name %></td>
              <td><%= p.title %></td>
              <td><%= p.created_at.to_s %></td>
              <td><%= link_to "Delete", user_post_path(p.user, p), :method => :delete, :confirm => "Are you sure you wanna delete your post?" if current_user && current_user.id == p.user.id %></td>
          </tr>
        <% end if @posts.present? %>
    </table>
</div>

app/views/posts/index.rss.erb
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>User Posts from Fantastic User Posts Site</title>
    <link><%= posts_url %></link>
    <description>A blog about everything and anyone</description>
    <% @posts.each do |post| %>
      <item>
          <title><%= post.title %></title>
          <full_name><%= post.full_name %></full_name>
          <created_at><%= post.created_at.to_s %></created_at>
          <link><%= user_post_url(:user_id => post.user.to_param, :id => post.to_param) %></link>
      </item>
    <% end unless @posts.nil? %>
  </channel>
</rss>

app/views/posts/more_posts.html.erb
<%= link_to "Number of new posts: #{@answer}", root_path if @answer >= 1%>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= error_messages_for :post, :id => 'error_explanation', :class => 'error_explanation' %>

<%= form_for [@post.user, @post] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Post Details(#<%= @post.id %>)</h1>
<%= "User: #{@post.user.full_name}" %><br/>
<%= "Post: #{@post.title}" %><br/>
<%= "Created at: #{@post.created_at}" %>

app/views/users/index.html.erb
<h1>List of Users:</h1>
<table>
    <tr><th>Index</th>
        <th>Id</th>
        <th>Name</th>
        <th>Phone</th>
        <th></th>
    </tr>

    <% record_counter = 0 %>
    <% @users.each do |u| %>
        <% record_counter += 1 %>
        <tr><td><%= record_counter %></td>
            <td><%= u.id  %></td>
            <td><%= u.full_name %></td>
            <td><%= u.phone %></td>
            <td><%= link_to "Posts", user_posts_path(u) %></td>
        </tr>
    <% end if @users.present?  %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= error_messages_for :user, :id => 'error_explanation', :class => 'error_explanation' %>

<%= form_for @user do |f|%>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.label :full_name %>
    <%= f.text_field :full_name %>

    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.submit %>
<% end %>